# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Troy Starwalt
email: troy.starwalt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a full-stack freelance web developer available for hire. Say hi!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://troystarwalt.co" # the base hostname & protocol for your site
twitter_username: troyst
github_username: troystarwalt
linkedin_username: troystarwalt

# Build settings
markdown: kramdown
gems: [jekyll-paginate]